## What is the version of Pandas installed?

In [1]:
import pandas as pd
import numpy as np
pd.__version__

'2.3.2'

## Read the dataset using pandas

In [2]:
df = pd.read_csv('car_fuel_efficiency.csv')
df.describe

<bound method NDFrame.describe of       engine_displacement  num_cylinders  horsepower  vehicle_weight  \
0                     170            3.0       159.0     3413.433759   
1                     130            5.0        97.0     3149.664934   
2                     170            NaN        78.0     3079.038997   
3                     220            4.0         NaN     2542.392402   
4                     210            1.0       140.0     3460.870990   
...                   ...            ...         ...             ...   
9699                  140            5.0       164.0     2981.107371   
9700                  180            NaN       154.0     2439.525729   
9701                  220            2.0       138.0     2583.471318   
9702                  230            4.0       177.0     2905.527390   
9703                  270            3.0       140.0     2908.043477   

      acceleration  model_year  origin fuel_type         drivetrain  \
0             17.7        2003

## How many records are in the dataset?

In [3]:
rows, columns = df.shape
print(f"Records: {rows}, Columns: {columns}")

Records: 9704, Columns: 11


## How many Fuel Types are there?

In [4]:
df['fuel_type'].value_counts()

fuel_type
Gasoline    4898
Diesel      4806
Name: count, dtype: int64

In [5]:
df['fuel_type'].nunique()

2

## How many columns in the dataset have missing values?

In [6]:
print("\nCount of NaN in each column:\n", df.isnull().sum())


Count of NaN in each column:
 engine_displacement      0
num_cylinders          482
horsepower             708
vehicle_weight           0
acceleration           930
model_year               0
origin                   0
fuel_type                0
drivetrain               0
num_doors              502
fuel_efficiency_mpg      0
dtype: int64


In [7]:
print(df.isnull().any().sum())

4


## What is the maximum fuel efficiency of cars from Asia?

In [8]:
max_fe_asia = df
selectedOrigin = max_fe_asia[max_fe_asia["origin"] == "Asia"]
maxValue = selectedOrigin["fuel_efficiency_mpg"].max()
filtered = selectedOrigin.sort_values(by=['fuel_efficiency_mpg'], ascending=False)
print(filtered)

      engine_displacement  num_cylinders  horsepower  vehicle_weight  \
9387                  330            3.0       136.0     1223.298226   
343                   240            2.0         NaN     1652.883753   
7739                  170           10.0       139.0     1491.755825   
9401                  110            1.0       183.0     1707.231276   
5416                  250            6.0       173.0     1354.787120   
...                   ...            ...         ...             ...   
2890                  240            4.0        92.0     4323.711871   
9120                  180            3.0       181.0     4661.144932   
6581                  150            NaN       148.0     4392.759292   
3891                  290            6.0       145.0     4481.764226   
1095                  210            6.0        93.0     4345.732510   

      acceleration  model_year origin fuel_type         drivetrain  num_doors  \
9387           NaN        2001   Asia  Gasoline  Front

In [9]:
print(maxValue)

23.759122836520497


## Find the median value of horsepower in the dataset

We'll be cleaning a bit of the data here, as there are null values in the horsepower column. First return the inital Median:

In [10]:
df['horsepower'].median()

149.0

Next, find the most frequent value (mode) of the horsepower column

In [11]:
df['horsepower'].mode()

0    152.0
Name: horsepower, dtype: float64

In [12]:
replaced = df['horsepower'].mode()[0]
replaced

np.float64(152.0)

Use fillna to replace the missing values with the most frequent:

In [13]:
df.fillna({'horsepower': replaced}, inplace = True)
df

engine_displacement  num_cylinders  horsepower  vehicle_weight  \
0                     170            3.0       159.0     3413.433759   
1                     130            5.0        97.0     3149.664934   
2                     170            NaN        78.0     3079.038997   
3                     220            4.0       152.0     2542.392402   
4                     210            1.0       140.0     3460.870990   
...                   ...            ...         ...             ...   
9699                  140            5.0       164.0     2981.107371   
9700                  180            NaN       154.0     2439.525729   
9701                  220            2.0       138.0     2583.471318   
9702                  230            4.0       177.0     2905.527390   
9703                  270            3.0       140.0     2908.043477   

      acceleration  model_year  origin fuel_type         drivetrain  \
0             17.7        2003  Europe  Gasoline    All-wheel drive   
1             17.8        2007     USA  Gasoline  Front-wheel drive   
2             15.1        2018  Europe  Gasoline  Front-wheel drive   
3             20.2        2009     USA    Diesel    All-wheel drive   
4             14.4        2009  Europe  Gasoline    All-wheel drive   
...            ...         ...     ...       ...                ...   
9699          17.3        2013  Europe    Diesel  Front-wheel drive   
9700          15.0        2004     USA  Gasoline    All-wheel drive   
9701          15.1        2008     USA    Diesel    All-wheel drive   
9702          19.4        2011     USA    Diesel  Front-wheel drive   
9703          14.7        2005    Asia    Diesel    All-wheel drive   

      num_doors  fuel_efficiency_mpg  
0           0.0            13.231729  
1           0.0            13.688217  
2           0.0            14.246341  
3           2.0            16.912736  
4           2.0            12.488369  
...         ...                  ...  
9699        NaN            15.101802  
9700        0.0            17.962326  
9701       -1.0            17.186587  
9702        1.0            15.331551  
9703       -1.0            14.884467  

[9704 rows x 11 columns]

In [14]:
df['horsepower'].isnull().sum()

np.int64(0)

Finally, return the median with the transformed data:

In [15]:
df['horsepower'].median()

152.0

Has it changed? (Yes, it increased)

## Sum of weights

First, select all the cars from Asia:

In [16]:
asia_cars = df
asia_cars = asia_cars[asia_cars["origin"] == "Asia"]
asia_cars

engine_displacement  num_cylinders  horsepower  vehicle_weight  \
8                     250            1.0       174.0     2714.219310   
12                    320            5.0       145.0     2783.868974   
14                    200            6.0       160.0     3582.687368   
20                    150            3.0       197.0     2231.808142   
21                    160            4.0       133.0     2659.431451   
...                   ...            ...         ...             ...   
9688                  260            4.0       152.0     3948.404625   
9692                  180            3.0       188.0     3680.341381   
9693                  280            2.0       148.0     2545.070139   
9698                  180            1.0       131.0     3107.427820   
9703                  270            3.0       140.0     2908.043477   

      acceleration  model_year origin fuel_type         drivetrain  num_doors  \
8             10.3        2016   Asia    Diesel  Front-wheel drive       -1.0   
12            15.1        2010   Asia    Diesel    All-wheel drive        1.0   
14            14.9        2007   Asia    Diesel    All-wheel drive        0.0   
20            18.7        2011   Asia  Gasoline  Front-wheel drive        1.0   
21             NaN        2016   Asia  Gasoline  Front-wheel drive       -1.0   
...            ...         ...    ...       ...                ...        ...   
9688          15.5        2018   Asia    Diesel    All-wheel drive       -1.0   
9692          18.0        2016   Asia  Gasoline  Front-wheel drive        1.0   
9693          15.6        2012   Asia    Diesel    All-wheel drive        0.0   
9698          13.2        2005   Asia  Gasoline  Front-wheel drive       -2.0   
9703          14.7        2005   Asia    Diesel    All-wheel drive       -1.0   

      fuel_efficiency_mpg  
8               16.823554  
12              16.175820  
14              11.871091  
20              18.889083  
21              16.077730  
...                   ...  
9688            11.054830  
9692            11.711653  
9693            17.202782  
9698            13.933716  
9703            14.884467  

[3247 rows x 11 columns]

Next, select only the columns of vehicle_weight and model_year:

In [17]:
asia_cars = asia_cars[['vehicle_weight', 'model_year']]
asia_cars

vehicle_weight  model_year
8        2714.219310        2016
12       2783.868974        2010
14       3582.687368        2007
20       2231.808142        2011
21       2659.431451        2016
...              ...         ...
9688     3948.404625        2018
9692     3680.341381        2016
9693     2545.070139        2012
9698     3107.427820        2005
9703     2908.043477        2005

[3247 rows x 2 columns]

Next, select the first 7 values:

In [18]:
asia_cars = asia_cars.head(7)
asia_cars

vehicle_weight  model_year
8      2714.219310        2016
12     2783.868974        2010
14     3582.687368        2007
20     2231.808142        2011
21     2659.431451        2016
34     2844.227534        2014
38     3761.994038        2019

Get the underlying NumPy array, and call it x:

In [19]:
x = asia_cars.to_numpy()
x

array([[2714.21930965, 2016.        ],
       [2783.86897424, 2010.        ],
       [3582.68736772, 2007.        ],
       [2231.8081416 , 2011.        ],
       [2659.43145076, 2016.        ],
       [2844.22753389, 2014.        ],
       [3761.99403819, 2019.        ]])

Compute matrix-matrix multiplication between the transpose of X and X. To get the transpose, use X.T. Let's call the result XTX.

In [20]:
xtx = x.T @ x

print(xtx)

[[62248334.33150762 41431216.50732678]
 [41431216.50732678 28373339.        ]]


Invert XTX:

In [21]:
xtx_inv = np.linalg.inv(xtx)
xtx_inv

array([[ 5.71497081e-07, -8.34509443e-07],
       [-8.34509443e-07,  1.25380877e-06]])

Create an array y with values [1100, 1300, 800, 900, 1000, 1100, 1200]:

In [22]:
y = np.array([1100, 1300, 800, 900, 1000, 1100, 1200])
y

array([1100, 1300,  800,  900, 1000, 1100, 1200])

Multiply the inverse of XTX with the transpose of X, and then multiply the result by y. Call the result w:

In [23]:
w = xtx_inv @ x.T @ y
w

array([0.01386421, 0.5049067 ])

What's the sum of all the elements of the result?

In [24]:
sum_of_w = np.sum(w)
sum_of_w

np.float64(0.5187709081074007)